### ISSUE TITLE
US 10 - Visualizar o número de postagens por status (arquivado, em andamento, em análise, resolvido) [User Story]

### ISSUE THREAD

**Issue by mansogf** [fga-eps-mds/2020.1-Grupo6#147]
**Descrição**

Elaborar visualização do número de postagens por status: arquivado, em andamento, em análise, resolvido.

**Screenshots**

<img width="746" alt="Captura de Tela 2020-11-10 às 10 11 59" src="https://user-images.githubusercontent.com/37154573/98678488-69cdbc00-233d-11eb-8fa0-ca3cfa71a284.png">

Caso haja necessidade, adicione screenshots para ajudá-lo a explicar.

**Tarefas**
- [x] [Visualizar número de publicações em andamento;](https://github.com/fga-eps-mds/2020.1-Grupo6/issues/201#issue-765720625)
- [x] [Visualizar número de publicações em análise;](https://github.com/fga-eps-mds/2020.1-Grupo6/issues/202#issue-765721957)
- [x] [Visualizar número de publicações resolvidas;](https://github.com/fga-eps-mds/2020.1-Grupo6/issues/203#issue-765723429)
- [x] [Visualizar número de publicações arquivadas;](https://github.com/fga-eps-mds/2020.1-Grupo6/issues/204#issue-765724417)

**Critérios de Aceitação**
- [x] Gerar dados no banco para enriquecer as visualizações
