### ISSUE TITLE
US 14 - Visualizar gráfico temporal (connected scatter) dos status das postagens criadas [User Story]

### ISSUE THREAD

**Issue by mansogf** [fga-eps-mds/2020.1-Grupo6#148]
**Descrição**

Elaborar gráficos _connected scatter_ dos staus das postagens criadas.

**Screenshots**

<img width="791" alt="Captura de Tela 2020-11-10 às 10 22 27" src="https://user-images.githubusercontent.com/37154573/98679461-d5fcef80-233e-11eb-8945-ea5b9978e9b9.png">
<img width="791" alt="Captura de Tela 2020-11-10 às 10 22 05" src="https://user-images.githubusercontent.com/37154573/98679464-d7c6b300-233e-11eb-972d-1e993c0bc148.png">
<img width="792" alt="Captura de Tela 2020-11-10 às 10 22 15" src="https://user-images.githubusercontent.com/37154573/98679467-dac1a380-233e-11eb-838a-97a0b975a8b4.png">

Caso haja necessidade, adicione screenshots para ajudá-lo a explicar.

**Tarefas**
- [x] Visualizar gráficos de publicações em andamento (registros diários, mensais, anuais) #201;
- [x] Visualizar gráficos de publicações em análise (registros diários, mensais, anuais) #202 ;
- [x] Visualizar gráficos de publicações resolvidas (registros diários, mensais, anuais) #203  ;
- [x] Visualizar gráficos de publicações arquivadas (registros diários, mensais, anuais) #204 ;

**Critérios de Aceitação**
- [x] Gerar dados no banco para enriquecer as visualizações
