### ISSUE TITLE
Refazer o Documento de Arquitetura

### ISSUE THREAD

**Issue by julianavalle** [fga-eps-mds/2020.1-Grupo6#157]
**Hotfix**

**Descrição**
Refazer o pontos citados abaixo do documento de arquitetura

*Representação Arquitetural*
- [x] [Explicar melhor como as tecnologias influenciam no projeto, além de ter uma descrição breve sobre elas.](https://github.com/fga-eps-mds/2020.1-Grupo6/issues/205)

*Banco de Dados*
- [x] [Refazer o banco de dados de acordo com o banco atual.](https://github.com/fga-eps-mds/2020.1-Grupo6/issues/206)

*Restrições e Metas Arquiteturais*
- [x] [As restrições e as metas não estão explícitas.](https://github.com/fga-eps-mds/2020.1-Grupo6/issues/207)

*Visão de Casos de Uso*
- [x] [Retirar essa parte do documento porque não é usado no projeto. O projeto utiliza histórias de usuário.](https://github.com/fga-eps-mds/2020.1-Grupo6/issues/208)

**Critérios de Aceitação**
- [x] Reescrever os tópicos.
