### ISSUE TITLE
[Refatoração] - Notícias

### ISSUE THREAD

**Issue by mansogf** [fga-eps-mds/2020.1-Grupo6#170]
**Descrição**

Issue para a refatoração e correção de bugs das Notícias

Caso haja necessidade, adicione screenshots para ajudá-lo a explicar.

**Tarefas**
- [x] [Ícone da Câmera como botão [Hotfix];](https://github.com/fga-eps-mds/2020.1-Grupo6/issues/158)
- [x] [Falhas na criação de notícias [Hotfix];](https://github.com/fga-eps-mds/2020.1-Grupo6/issues/159)
- [x] [Direcionar após criação da notícia [Hotfix];](https://github.com/fga-eps-mds/2020.1-Grupo6/issues/160)
- [x] [Ícones de exclusão não funcionam [Hotfix];](https://github.com/fga-eps-mds/2020.1-Grupo6/issues/161)
- [x] [Link das postagens com as notícias não funciona [Hotfix]](https://github.com/fga-eps-mds/2020.1-Grupo6/issues/173)

**Critérios de Aceitação**
- [ ] A correção de todos os bugs encontrados
