### ISSUE TITLE
Alterar fontes, cores, página inicial e datas do relatório de dados [HOTFIX]

### ISSUE THREAD

**Issue by julianavalle** [fga-eps-mds/2020.1-Grupo6#186]
**Descrição**

Alterar as fontes e cores do projeto de acordo com o manual de identidade visual da UnB.

**Tarefas**
- [x] Alterar as fontes #196 
- [x] Alterar as cores #197 
- [x] Alterar página inicial para a página de Relatório de Dados #198
- [x] Colocar "a partir" nas datas do Relatório de Dados #199
