### ISSUE TITLE
Checklist de artefatos

### ISSUE THREAD

**Issue by mansogf** [fga-eps-mds/2020.1-Grupo6#29]
Por meio de uma reunião foi discutido que deveria ser feito um checklist de todos os artefatos do projeto para melhor planejamento.

# CHECKLIST DE ARTEFATOS

- [x] Mapear onde cada artefato influencia nas fases do PMBOK

- [x] Apresentação do Tema e do Projeto (Atualizar git pages e wiki)
- [x] Roadmap
- [x] Priorização e pontuação dos requisitos
- [x] Estrutura da Sprint 
- [x] Documento de Arquitetura do Projeto;

- [x] Especificação das historias de usuários (critérios de aceitação);
- [x]  Backlog do Produto
- [x] Planejamento/Comunicação Interna e Externa (agenda de trabalho + ferramentas);
- [x] Documento de Visão do Projeto;
- [x] Planejamento e Histórico das Sprints
- [x] TAP
- [x] EAP;
- [x] Artefatos de monitoramento (pĺanilha de horarios disponíveis, horas trabalhadas, quadro de conhecimento)
- [x] Configuração do repositório de acordo com os padrões de comunidade de software livre (Github);

**Comment by mansogf** [comment]
Galera ( @Mateusas3s @Guilherme-Aguiar ), aqui estão os artefatos que conversamos em nossa reunião. Sugiro que:

1. Caso esteja faltando algum artefato, comente aqui e adicione no checklist;
2. Sugiro que após a finalização do checklist trabalhemos com priorização;
3. Após a priorização, sejam definidos os times para trabalhar em cada documento;

![](https://media.giphy.com/media/cFkiFMDg3iFoI/giphy.gif)
